xgui : Other/xgui/**/*.rkt
	chmod +x ./Other/remove-existing-pkg.sh && ./Other/remove-existing-pkg.sh && cd Other/xgui && raco pkg install --auto --skip-installed  && raco exe -o xgui xgui.rkt && mv xgui ../../
