name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Run Milestone A tests -- can delete once Milestone A is complete
  test-A:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.9'

      - name: Install Library and Dependencies
        working-directory: ./A/Other
        run: raco pkg install --auto --skip-installed

      - name: Run Unit Tests
        working-directory: ./A/Other
        run: raco test xjson.rkt

      - name: Build Binary
        working-directory: ./A
        run: make

      - name: Run Integration Tests
        working-directory: ./A/Other
        run: chmod +x test.sh && ./test.sh
